export default [
	// {
	// 	id: 1,
	// 	header: "Cover page",
	// 	type: "Cover page",
	// 	status: "In Process",
	// 	target: "18",
	// 	limit: "5",
	// 	reviewer: "Eddie Lake",
	// },
	//Note: Don't have duplicate IDs, or the page break lol
	//TODO: Add a link to the blog post, update dates, add images
	{
		id: 1,
		title: "First Blog Post", 
		slug: "first-blog-post",
		date: "2024-06-15",
		summary: "This is the first blog post",
		author: "Vincent Hilario",
		category: "Personal Reflection",
		image: "https://placehold.co/400",
		link: "TBD",
	tags: ["vincent", "life"]
	},
	{
		id: 2,
		title: "Second Blog Post",
		slug: "second-blog-post",
		date: "2024-09-03", 
		summary: "This is the second blog post",
		author: "Vincent Hilario",
		category: "Technical Article",
		tags: ["sveltekit", "react"],
	},
	{
		id: 3,
		title: "Third Blog Post",
		slug: "third-blog-post",
		date: "2020-01-12",
		summary: "This is the third blog post", 
		author: "Vincent Hilario",
		category: "Test Blog Post",
		image: "https://placehold.co/1600x900",
		tags: ["idk", "stuff"],
	},
	{
		id: 4,
		title: "My Best Purchases in 2024",
		slug: "my-best-purchases-in-2024",
		date: "2025-01-23",
		summary: "2024 was a year of growth and change for me. I made some great purchases that helped me improve my life and my health. Here are some of my best purchases from the year.",
		author: "Vincent Hilario",
		category: "Personal Reflection",
		image: "https://placehold.co/1600x900",
		tags: ["wellness", "life"],
	},
	{
		id: 5,
		title: "My Fitness Journey",
		slug: "my-fitness-journey",
		date: "2025-05-29",
		summary: "In August 2024, I finally decided to start taking care of my health. Here's some of the things I've learned along the way.",
		author: "Vincent Hilario",
		category: "Personal Reflection",
		image: "https://placehold.co/1600x900",
		tags: ["wellness", "life"],
	},
	{
		id: 6,
		title: "How Svelte Made Me Stop Using React",
		slug: "how-svelte-stole-my-heart",
		date: "2025-03-05",
		summary: "It's really good, but I'm not sure if it'll get me a job.",
		author: "Vincent Hilario",
		category: "Technical Article",
		image: "https://placehold.co/1600x900",
		tags: ["svelte", "webdev"],
	},
	{
		id: 7,
		title: "Grinding LeetCode, Ugh.",
		slug: "grinding-leetcode-ugh",
		date: "2025-02-17",
		summary: "It makes me hate the player AND the game.",
		author: "Vincent Hilario",
		category: "Personal Reflection",
		image: "https://placehold.co/1600x900",
		tags: ["leetcode", "job-hunting"],
	},
	{
		id: 8,
		title: "The Harbor Freight Database",
		slug: "the-harbor-freight-database",
		date: "2021-01-30",
		summary: "My first real group coding project, built for my Software Development class at UT Tyler.",
		author: "Vincent Hilario",
		category: "Project Overview",
		image: "https://placehold.co/1600x900",
		tags: ["project", "software-dev"],
	},
	{
		id: 9,
		title: "I Want To Make a Daily Game",
		slug: "i-want-to-make-a-daily-game",
		date: "2025-05-29",
		summary: "Read about my struggle to think of a good game idea.",
		author: "Vincent Hilario",
		category: "Personal Reflection",
		image: "https://placehold.co/1600x900",
		tags: ["games", "nyt"],
	},
	{
		id: 10,
		title: "I'm Addicted to Daily Games",
		slug: "im-addicted-to-daily-games",
		date: "2025-05-29",
		summary: "Here's my justification for why I don't think that's a bad thing.",
		author: "Vincent Hilario",
		category: "Personal Reflection",
		image: "https://placehold.co/1600x900",
		tags: ["games", "nyt"],
	},
	{
		id: 11,
		title: "My Gaming Hobby",
		slug: "my-gaming-hobby",
		date: "2025-05-29",
		summary: "Gaming has been a part of my life since I was old enough to hold a controller. Here's a look into my history with the entertainment medium.",
		author: "Vincent Hilario",
		category: "Personal Reflection",
		image: "https://placehold.co/1600x900",
		tags: ["games", "vincent"],
	},
	{
		id: 12,
		title: "This Website: A Journey of Self-Taught Web Development",
		slug: "this-website-a-journey-of-self-taught-web-development",
		date: "2025-05-29",
		summary: "I built this website using SvelteKit, Shadcn-svelte, and Tailwind CSS. Here's an overview of things that went right and wrong.",
		author: "Vincent Hilario",
		category: "Project Overview",
		image: "https://placehold.co/1600x900",
		tags: ["webdev", "sveltekit"],
	},
	{
		id: 13,
		title: "Things I Wish I Knew When I Was 20",
		slug: "things-i-wish-i-knew-when-i-was-20",
		date: "2025-04-06",
		summary: "Oh, man. How time flies. I'm 24 now, and my brain is apparently almost done developing. Anyway, here's what I would tell myself if I could go back in time.",
		author: "Vincent Hilario",
		category: "Personal Reflection",
		image: "https://placehold.co/1600x900",
		tags: ["life", "vincent"],
	},

];
