export default [
	// {
	// 	id: 1,
	// 	header: "Cover page",
	// 	type: "Cover page",
	// 	status: "In Process",
	// 	target: "18",
	// 	limit: "5",
	// 	reviewer: "Eddie Lake",
	// },
	//Note: Don't have duplicate IDs, or the page break lol
	//TODO: Add a link to the blog post, update dates, add images
	{
		id: 1,
		title: "First Blog Post", 
		date: "2024-06-15",
		summary: "This is the first blog post",
		author: "Vincent Hilario",
		category: "Personal Reflection",
		image: "https://placehold.co/400",
		link: "TBD",
	tags: ["vincent", "life"]
	},
	{
		id: 2,
		title: "Second Blog Post",
		date: "2024-09-03", 
		summary: "This is the second blog post",
		author: "Vincent Hilario",
		category: "Technical Article",
		tags: ["sveltekit", "react"],
	},
	{
		id: 3,
		title: "Third Blog Post",
		date: "2025-01-12",
		summary: "This is the third blog post", 
		author: "Vincent Hilario",
		category: "Test Blog Post",
		image: "https://placehold.co/1600x900",
		tags: ["idk", "stuff"],
	},
	{
		id: 4,
		title: "My Best Purchases in 2024",
		date: "2025-01-23",
		summary: "2024 was a year of growth and change for me. I made some great purchases that helped me improve my life and my health. Here are some of my best purchases from the year.",
		author: "Vincent Hilario",
		category: "Personal Reflection",
		image: "https://placehold.co/1600x900",
		tags: ["wellness", "life"],
	},
	{
		id: 5,
		title: "My Fitness Journey",
		date: "2025-05-29",
		summary: "In August 2024, I finally decided to start taking care of my health. Here's some of the things I've learned along the way.",
		author: "Vincent Hilario",
		category: "Personal Reflection",
		image: "https://placehold.co/1600x900",
		tags: ["wellness", "life"],
	},
	{
		id: 6,
		title: "How Svelte Stole My Heart",
		date: "2025-03-05",
		summary: "It's really good, but I'm not sure if it'll get me a job.",
		author: "Vincent Hilario",
		category: "Technical Article",
		image: "https://placehold.co/1600x900",
		tags: ["svelte", "webdev"],
	},
	{
		id: 7,
		title: "Grinding LeetCode, Ugh.",
		date: "2025-02-17",
		summary: "It makes me hate the player AND the game.",
		author: "Vincent Hilario",
		category: "Personal Reflection",
		image: "https://placehold.co/1600x900",
		tags: ["leetcode", "job-hunting"],
	},
	{
		id: 8,
		title: "The Harbor Freight Database",
		date: "2021-01-30",
		summary: "My first real group coding project, built for my Software Development class at UT Tyler.",
		author: "Vincent Hilario",
		category: "Project Overview",
		image: "https://placehold.co/1600x900",
		tags: ["project", "software-development"],
	},
	{
		id: 9,
		title: "I'm Addicted to The New York Times Games",
		date: "2025-05-29",
		summary: "Here's my justification for why I don't think that's a bad thing.",
		author: "Vincent Hilario",
		category: "Personal Reflection",
		image: "https://placehold.co/1600x900",
		tags: ["games", "nyt"],
	},
	{
		id: 10,
		title: "I'm Addicted to Daily Games",
		date: "2025-05-29",
		summary: "Here's my justification for why I don't think that's a bad thing.",
		author: "Vincent Hilario",
		category: "Personal Reflection",
		image: "https://placehold.co/1600x900",
		tags: ["games", "nyt"],
	},
	{
		id: 11,
		title: "My Gaming Hobby",
		date: "2025-05-29",
		summary: "Gaming has been a part of my life since I was old enough to hold a controller. Here's a look into my history with the entertainment medium.",
		author: "Vincent Hilario",
		category: "Personal Reflection",
		image: "https://placehold.co/1600x900",
		tags: ["games", "vincent"],
	},

];
